runtime: php82
env: flex
entrypoint: serve public/index.php

runtime_config:
  document_root: public

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

env_variables:
  APP_ENV: production
  APP_KEY: base64:p0EdZe1sa1iOrE1GsjYTXUPoyWcuX6r4vvaspDGAMdI
  APP_DEBUG: false
  APP_LOG_LEVEL: info
  STORAGE_DIR: /tmp
